name: Example
on:
  pull_request:
    branches:
      - master
      - main
      - develop
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags to facilitate the merge.

      - name: Merge base branch into PR
        run: |
          # Fetch the latest commits from the base branch
          git fetch origin ${{ github.base_ref }}
          # Merge the base branch into the PR branch
          git merge origin/${{ github.base_ref }}

      - uses: matlab-actions/setup-matlab@v2

      - name: Set MATLAB license environment variable
        run: echo "MLM_LICENSE_FILE=/usr/local/MATLAB/R2024a/licenses/license_king_41220376_R2024a.lic" >> $GITHUB_ENV

      - name: Run basic MATLAB command
        run: matlab -batch "disp('Hello, World!')"

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: testReport.junit.xml  
