name: Example
on:
  pull_request:
    branches:
      - master
      - main
      - develop
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge base branch into PR
        run: |
          git fetch origin ${{ github.base_ref }}
          git merge origin/${{ github.base_ref }}

      - name: Run MATLAB Tests
        run: |
          matlab -batch "run('initCobraToolbox.m'); run('test/testAll.m');"

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: testReport.junit.xml  
