name: MATLAB Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: self-hosted
    steps:
    
    - name: Checkout PR Code
      uses: actions/checkout@v4

    - name: Merge PR with Develop
      run: |
        git fetch origin develop
        git checkout -b test-branch
        git merge origin/develop --no-edit

    - name: Clone COBRA Toolbox
      run: |
        git clone https://github.com/opencobra/cobratoolbox.git cobratoolbox

    - name: Run MATLAB Tests
      run: |
        matlab -batch "run('cobratoolbox/initCobraToolbox.m'); diary('test_results.txt'); run('cobratoolbox/runTestsAndGenerateReport.m'); diary off;"

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test_results.txt
